name: sharepoint-indexing
channels:
  - conda-forge
  - defaults
  - jupyter
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - pip:
    - -r requirements.txt
    - -r requirements-codequality.txt

